### PR TITLE
API-1661 TinyBlazorAdmin update to .NET 8.0

### PR DESCRIPTION
**Pull request by davecw2**

### CODE REVIEW

**Review by SteveDurkee — APPROVED** [review]
good upgrade

**Review by mattisax — APPROVED** [review]
Thanks @davecw2!

**Comment by mattisax** [comment]
@jem41 Adding you to see if anything else needs to be done for deployment. I'll leave it to you to merge.

**Review by jem41 — APPROVED** [review]
Looks good to me.

**Pull request merged**
