### PR TITLE
UrlShortner function only

### PR DESCRIPTION
**Pull request by mattisax**
Removed the Static Web App project and functions we do not need. Removed the Claims check from the UrlShortner function. Deployed to a new function app from VS, added the UlsDataStorage application config with the connection string to the Azure Storage account Joe deployed, then called the function from Postman. A shortened url was created.

@jem41 This has the same two application config settings that the Static Web App had. customDomain and UlsDataStorage.

### CODE REVIEW

**Review by jem41 — APPROVED** [review]
Looks good to me with a question.

Do we want to keep the UrlArchive to invalidate old short links? Azure Table Storage keys don't have expiration, so these urls would be active until manually deleted or archived

> @jem41 This has the same two application config settings that the Static Web App had. customDomain and UlsDataStorage.

Did we ever decide on an actual `customDomain` name?

**Comment by jem41** [comment]
> Do we want to keep the UrlArchive to invalidate old short links? Azure Table Storage keys don't have expiration, so these urls would be active until manually deleted or archived

Thinking about it, we wouldn't have a way to iterate over the keys to automate a bulk archive utility without UrlList or accessing the storage account directly from the services

**Comment by mattisax** [comment]
> Do we want to keep the UrlArchive to invalidate old short links? Azure Table Storage keys don't have expiration, so these urls would be active until manually deleted or archived

@jem41 Good point. Either that or we interact directly with the Table Storage directly (via API). Either way, we will need something to actually call the archive function.

@kthompson23 Do we have anything in the services that runs on a schedule? My initial thought is that this would be easier to do with an Azure Automation Runbook or even a time triggered Azure function.

**Comment by kthompson23** [comment]
> @kthompson23 Do we have anything in the services that runs on a schedule? My initial thought is that this would be easier to do with an Azure Automation Runbook or even a time triggered Azure function.

No services but we have a couple utilities that we package and deploy as Kubernetes CronJobs. These are in separate repositories. Whatever you think is easiest is fine with me.

**Comment by mattisax** [comment]
I added a new function, `UrlPurger`. This is a Time Triggered function set to run once a day at 6:00 UTC. It selects `ShortUrl` entities with created at Timestamp less than 7 days from the current datetime. Our TTL in the OverrideAuthorization db collection is 7 days.
@jem41 We can merge your PR today and then this one.

**Pull request merged**
